name: cotopay
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  share_plus: ^11.1.0
  url_launcher: ^6.2.6
  mobile_scanner: ^5.1.1
  audioplayers: ^6.0.0
  intl: ^0.19.0
  file_picker: ^8.0.5
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  encrypt: ^5.0.3
  http: ^1.2.1
  pem: ^2.0.0
  convert: ^3.1.1
  crypto: ^3.0.2
  basic_utils: ^5.6.1
  shared_preferences: ^2.2.2
  pointycastle: ^3.6.2
  asn1lib: ^1.1.1
  flutter_cashfree_pg_sdk: 2.2.9+47
  flutter_svg: ^2.0.0



  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  lottie: ^3.1.2
  provider: ^6.1.1

  # UI package
  fluttertoast: ^8.2.12
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/otp_logo.png
    - assets/images/bank.png
    - assets/logo.png
    - assets/lottie/
    - assets/sound/
    - assets/add_icon.png
    - assets/avatar.png
    - assets/issue_icon.png
    - assets/logo.png
    - assets/no_offers.png
    - assets/no_vouchers.webp
    - assets/offer_icon.png
    - assets/scan.png
    - assets/upi_logo.svg
    - assets/voucher_illustration.png
    - assets/images/info.png
    - assets/images/revoke.png
    - assets/India.png
    - assets/home_b.png
    - assets/offer_b.png
    - assets/his_b.png
    - assets/delete.png
    - assets/coto_icon.png
    - assets/magic_icon.png
    - assets/coto_logo_top.png
    - assets/img_back_fram.png
    - assets/info.svg
    - assets/revoke.svg
    - assets/scan.svg
    - assets/home_b.svg
    - assets/voucher_b.svg
    - assets/offer_b.svg
    - assets/his_b.svg
    - assets/issue_icon.svg
    - assets/add_icon.svg
    - assets/offer_icon.svg
    - assets/arrow.svg
    - assets/arr.svg
    - assets/single.svg
    - assets/multiple.svg
    - assets/left_line.svg
    - assets/link_side.svg
    - assets/arro_side.svg
    - assets/key.svg
    - assets/about.svg
    - assets/terms.svg
    - assets/profile_card.svg
    - assets/edit.svg
    - assets/app_bar_back.svg
    - assets/expand.svg
    - assets/bank.svg
    - assets/isue_vou.svg
    - assets/apr.svg
    - assets/countvc.svg
    - assets/delete.svg
    - assets/single_black.svg
    - assets/multiple_black.svg
    - assets/checked.svg
    - assets/righ.svg
    - assets/genspend.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

  dependency_overrides:
    permission_handler_android: ^10.4.0